# Generated by Django 4.2.3 on 2023-07-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchain",
            name="data",
            field=models.CharField(max_length=25500),
        ),
        migrations.DeleteModel(name="Block",),
    ]
