# Generated by Django 4.2.3 on 2023-07-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analyst", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readonlydocument",
            name="file",
            field=models.FileField(upload_to="ReadOnlyDocument/"),
        ),
    ]
