# Generated by Django 4.2.3 on 2023-07-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Analyst", "0002_alter_readonlydocument_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readonlydocument", old_name="owner", new_name="reader",
        ),
    ]
