# Generated by Django 4.2.3 on 2023-07-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Owner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="key",
            field=models.CharField(default="", max_length=200),
        ),
    ]
